---

- name: hostname - set
  hostname:
    name: '{{ bootstrap_hostname }}'
  when: bootstrap_hostname is defined and bootstrap_hostname|length > 0

- name: hostname - hosts
  lineinfile:
    state: present
    dest: /etc/hosts
    regexp: '{{ "^" + (bootstrap_ipv4 | default("127.0.1.1")) | replace(".","\.") }}'
    line: '{{ (bootstrap_ipv4 | default("127.0.1.1")) + "\t" + (bootstrap_hostname | default(ansible_hostname)) + "." + bootstrap_domain + "\t" + (bootstrap_hostname | default(ansible_hostname)) }}'
  when: bootstrap_domain is defined and bootstrap_domain


