---

- name: get hostname
  shell: hostname --fqdn || hostname
  register: initial_hostname
  changed_when: False

- name: set host name
  include: hostname.yml

- name: get hostname
  shell: hostname --fqdn || hostname
  register: check_hostname
  changed_when: initial_hostname.stdout != check_hostname.stdout

- name: dependencies
  include: depend.yml

- name: setup global vim
  include: vim.yml

- name: restart machine
  shell: sleep 2 && shutdown -r now "Ansible role basics triggered"
  async: 10
  poll: 0
  ignore_errors: true
  when: initial_hostname.stdout != check_hostname.stdout

- name: pausing 20 seconds
  pause: seconds=20
  when: initial_hostname.stdout != check_hostname.stdout

- name: waiting for server to come back
  wait_for: >
      host={{ ansible_default_ipv4['address'] }}
      port=22
      delay=5
      timeout=300
      state=started
  sudo: false
  delegate_to: localhost
  when: initial_hostname.stdout != check_hostname.stdout

