---

- name: get hostname
  shell: hostname --fqdn || hostname
  register: initial_hostname
  changed_when: False

- name: set host name
  include: hostname.yml

- name: get hostname
  shell: hostname --fqdn || hostname
  register: check_hostname
  changed_when: initial_hostname.stdout != check_hostname.stdout

- name: dependencies
  include: depend.yml

- name: setup global vim
  include: vim.yml

- name: restart machine
  shell: sleep 2 && shutdown -r now "Ansible role basics triggered"
  async: 10
  poll: 0
  ignore_errors: true
  when: initial_hostname.stdout != check_hostname.stdout

- name: waiting for server to come back
  local_action:
    module: wait_for
      host={{ inventory_hostname }}
      port=22
      delay=1
      timeout=300
      state=started
  sudo: false
  when: initial_hostname.stdout != check_hostname.stdout
