---

- name: get hostname
  shell: hostname --fqdn
  register: initial_hostname
  changed_when: False

- name: set host name
  include: hostname.yml

- name: get hostname
  shell: hostname --fqdn
  register: check_hostname
  changed_when: initial_hostname.stdout != check_hostname.stdout

- name: dependencies
  include: depend.yml

- name: setup global vim
  include: vim.yml

- name: restart machine
  command: shutdown -r now "Ansible role basics triggered"
  async: 0
  poll: 0
  ignore_errors: true
  when: initial_hostname.stdout != check_hostname.stdout

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }}
                state=started
  sudo: false
  when: initial_hostname.stdout != check_hostname.stdout
